[project]
name = "dolores"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langfuse>=3.0.1",
    "lmstudio>=1.3.1",
    "python-dotenv>=1.1.0",
    "python-telegram-bot>=22.1",
]

[tool.ruff.lint]
select = ["ALL"]
